del /f ..\bin\shader*.dll
del /f ..\bin\stdshader*.dll
del /f ..\hl2\bin\client.dll
del /f ..\hl2\bin\server.dll
del /f ..\hl2\bin\gameui.dll
del /f ..\tf2\bin\client.dll
del /f ..\tf2\bin\server.dll
del /f ..\tf2\bin\gameui.dll
del /f ..\hl1\bin\client.dll
del /f ..\hl1\bin\server.dll
del /f ..\hl1\bin\gameui.dll
del /f ..\cstrike\bin\client.dll
del /f ..\cstrike\bin\server.dll
del /f ..\cstrike\bin\gameui.dll
del /f ..\hlds.exe
del /f ..\bin\hlds.exe
del /f ..\bin\hlds.dat
del /f ..\hl2.exe
del /f ..\tf2.exe
del /f ..\hl2.dat
del /f ..\tf2.dat
del /f ..\bin\FileSystem_Stdio.dll
del /f ..\bin\FileSystem_Steam.dll
del /f ..\bin\tier0.dll
del /f ..\bin\MaterialSystem.dll
del /f ..\bin\bsppack.dll
del /f ..\bin\dbg.dll
del /f ..\bin\engine.dll
del /f ..\bin\launcher.dll
del /f ..\bin\makevfont.dll
del /f ..\bin\platform.dll
del /f ..\bin\shaderapidx8.dll
del /f ..\bin\shaderapidx9.dll
del /f ..\bin\shaderapiempty.dll
del /f ..\bin\studiorender.dll
del /f ..\bin\unitlib.dll
del /f ..\bin\vgui2.dll
del /f ..\bin\vguimatsurface.dll
del /f ..\bin\vphysics.dll
del /f ..\bin\vrad.dll
del /f ..\bin\vtex.dll
del /f ..\bin\wc.exe
del /f ..\bin\vbspinfo.exe
del /f ..\bin\vbsp.exe
del /f ..\bin\vrad.exe
del /f ..\bin\vrad.dll
del /f ..\bin\vvis.exe
del /f ..\bin\vvis.dll
del /f ..\bin\vaudio_miles.dll
del /f lib\common\mxtk.lib
del /f lib\public\vtf.lib
del /f lib\public\nvtristrip.lib
del /f lib\public\tier0.lib
del /f lib\public\vstdlib.lib
del /f ..\bin\vstdlib.dll
del /f lib\public\unitlib.lib
del /f lib\public\vgui_controls.lib
del /f lib\public\vgui_surfacelib.lib
del /f lib\public\appframework.lib
del /f ..\bin\playback.exe
del /f ..\bin\scratchpad3dviewer.exe
del /f ..\bin\studiomdl.exe
del /f ..\bin\hlmv.exe
del /f ..\bin\hlfaceposer.exe
del /f ..\bin\newdat.exe
del /f ..\bin\vtex.exe
del /f ..\bin\vtex.dll
del /f ..\bin\unittest.*
del /f ..\bin\bsppack.dll
del /f ..\bin\bspzip.exe
del /f ..\bin\height2normal.exe
del /f ..\bin\vtf2tga.exe
del /f ..\platform\servers\serverbrowser.dll
del /f ..\bin\scenemanager.exe
del /f ..\bin\bugreporter.dll
del /f ..\bin\phonemeextractors\*.dll

