..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\public
copy ..\..\public\list.h \ihvtest1\src\public
..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\public\tier0
copy ..\..\public\tier0\*.h \ihvtest1\src\public\tier0
copy ..\..\public\worldsize.h \ihvtest1\src\public
copy ..\..\public\vector.h \ihvtest1\src\public
copy ..\..\public\vector2d.h \ihvtest1\src\public
copy ..\..\public\vector4d.h \ihvtest1\src\public
copy ..\..\public\vmatrix.* \ihvtest1\src\public
copy ..\..\public\vplane.h \ihvtest1\src\public
copy ..\..\public\basetypes.h \ihvtest1\src\public
copy ..\..\public\interface.* \ihvtest1\src\public
copy ..\..\public\utlvector.* \ihvtest1\src\public
copy ..\..\public\utlmemory.* \ihvtest1\src\public
copy ..\..\public\utlstack.* \ihvtest1\src\public
copy ..\..\public\utlbuffer.cpp \ihvtest1\src\public
copy ..\..\public\utlbuffer.h \ihvtest1\src\public
copy ..\..\public\utlsymbol.* \ihvtest1\src\public
copy ..\..\public\utlrbtree.* \ihvtest1\src\public
copy ..\..\public\bumpvects.h \ihvtest1\src\public
copy ..\..\public\mathlib.* \ihvtest1\src\public
copy ..\..\public\imageloader.cpp \ihvtest1\src\public
copy ..\..\public\imageloader.h \ihvtest1\src\public
copy ..\..\public\tgaloader.cpp \ihvtest1\src\public
copy ..\..\public\tgaloader.h \ihvtest1\src\public
copy ..\..\public\tgawriter.* \ihvtest1\src\public
copy ..\..\public\filesystem.* \ihvtest1\src\public
copy ..\..\public\resource_file.* \ihvtest1\src\public
copy ..\..\public\mempool.* \ihvtest1\src\public
copy ..\..\public\crtmemdebug.* \ihvtest1\src\public
copy ..\..\public\strtools.* \ihvtest1\src\public
copy ..\..\public\pixelwriter.* \ihvtest1\src\public
copy ..\..\public\s3_intrf.h.* \ihvtest1\src\public
copy ..\..\public\amd3dx.h.* \ihvtest1\src\public
copy ..\..\public\s3tc.lib \ihvtest1\src\public
copy ..\..\public\clientstats.* \ihvtest1\src\public
copy ..\..\public\IStudioRender.h \ihvtest1\src\public
copy ..\..\public\studio.h \ihvtest1\src\public
copy ..\..\public\model_types.h \ihvtest1\src\public
copy ..\..\public\measure_section.* \ihvtest1\src\public
copy ..\..\public\fasttimer.* \ihvtest1\src\public
copy ..\..\public\convar.* \ihvtest1\src\public
copy ..\..\public\characterset.* \ihvtest1\src\public
copy ..\..\public\bspfile.* \ihvtest1\src\public
copy ..\..\public\utllinkedlist.* \ihvtest1\src\public
copy ..\..\public\cmodel.* \ihvtest1\src\public
copy ..\..\public\plane.* \ihvtest1\src\public
copy ..\..\public\trace.* \ihvtest1\src\public
copy ..\..\public\bspflags.* \ihvtest1\src\public
copy ..\..\public\vcollide.* \ihvtest1\src\public
copy ..\..\public\vtex_common.* \ihvtest1\src\public
copy ..\..\public\collisionutils.* \ihvtest1\src\public
..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\public\appframework
copy ..\..\public\appframework\*.* \ihvtest1\src\public\appframework
..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\public\vstdlib
copy ..\..\public\vstdlib\*.* \ihvtest1\src\public\vstdlib
..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\public\vtf
copy ..\..\public\vtf\*.* \ihvtest1\src\public\vtf


