..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\materialsystem
copy ..\..\materialsystem\BaseTimesMod2xEnvMap.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\Debug*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\unlitgeneric*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\unlitgeneric*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\vertexlitgeneric*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\wireframe.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\cmaterial*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\cmaterial*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\color*.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\color*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\cshader.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\ctexture.cpp \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\imagepacker.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\materialsystem_global.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\shader.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\shadersystem.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\imaterial*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\ishader*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\imesh*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\shaderapi.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\materialsystem*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\cshader.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\itexture*.h \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\ctexture*.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\random.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\texturemanager.* \ihvtest1\src\materialsystem\
copy ..\..\materialsystem\materialsystemihvtest.dsp \ihvtest1\src\materialsystem\materialsystem.dsp
copy ..\..\materialsystem\shaderdx8\*.vsh \ihvtest1\src\materialsystem\shaderdx8
..\..\devtools\bin\perl ..\..\..\..\bin\makedirhier.pl \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\perl.exe \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\perl*.dll \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\vsh_prep.pl \ihvtest1\src\devtools\bin
copy ..\..\devtools\bin\vsa.exe \ihvtest1\src\devtools\bin
mkdir \ihvtest1\src\materialsystem\shaderdx8\vshtmp
..\..\devtools\bin\perl ..\..\..\bin\makedirhier.pl \ihvtest1\src\public\materialsystem
copy ..\..\public\materialsystem\*.* \ihvtest1\src\public\materialsystem

